server:
  port: 9093

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/meta_db
    username: latifa
    password: latifa123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect



meta:
  app:
    client-id: "700843612954198"
    client-secret: "8e3773ff643a9be8703e65b26497a580"
  api:
    token:
      refresh:
        url: "https://graph.facebook.com/v18.0/oauth/access_token"
  page-id: "573298425861173"
  instagram-account-id: "9876543210"
  ad-account-id: "act_121780531366304"